config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :new, :create, :show] do
    resources :doses, only: [:index, :new, :create]
  end
  resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  # before_action :set_cocktail, only: [:show, :edit, :update, :destroy]

  def index
    @cocktails = Cocktail.all
    @cocktail = Cocktail.new
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail, notice: 'Cocktail was successfully created.'
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
    @cocktail = Cocktail.find(params["cocktail_id"])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params["cocktail_id"])
    if @dose.save
      redirect_to cocktail_path(@dose.cocktail), notice: 'Dose was successfully added.'
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy!
    redirect_to @dose.cocktail
  end

  private

  def dose_params
    params.require("dose").permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="container">
<div class="title">
  <h1>Drink Therapy</h1>
</div>

<div class="card-container">

  <% @cocktails.each do |cocktail| %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
      <%= link_to cocktail.name, cocktail_path(cocktail) %>
    </div>
  <% end %>
</div>

  <div class="new-simple-form">
    <%= simple_form_for [ @cocktail ] do |f| %>
      <%= f.input :name %>
      <%= f.submit "Create Cocktail", class: "btn btn-primary" %>
    <% end %>
  </div>


</div>

app/views/cocktails/new.html.erb
<div class="container">
  <h1>Cocktails#new</h1>
  <p>Find me in app/views/cocktails/new.html.erb</p>

  <div class="new-simple-form">
    <%= simple_form_for [ @cocktail ] do |f| %>
      <%= f.input :name %>
      <%= f.submit "Create Cocktail", class: "btn btn-success" %>
    <% end %>
  </div>

  <%= link_to 'Back to Cocktails', cocktails_path %>

</div>

app/views/cocktails/show.html.erb
<div class="container">

  <div class="card-product">
    <div class="banner">
      <!-- <img src="https://unsplash.com/photos/c9N-57Is7LA" alt="cocktail pic"> -->
      <h1><%= @cocktail.name %></h1>
    </div>
    <div class="card-info">
      <div class="description">

      </div>
      <div class="ingredients">
        <ul>
        <!-- list doses -->
        <%  @cocktail.doses.each do |dose|%>

        <li><%= Ingredient.find(dose.ingredient_id).name %> -- <%= dose.description.upcase %><%= link_to "🗑", dose_path(dose.id), method: :delete %></li>
        <% end %>
        </ul>
      </div>

    </div>
  </div>

  <div class="doses-container">
    <div class="add-doses">
      <h4>Add more Doses:</h4>
      <div>
        <div class="new-simple-form">
          <%= simple_form_for [ @cocktail, @dose] do |f| %>
            <%= f.association :ingredient %>
            <%= f.input :description %>
            <%= f.submit "Add dose", class: "btn btn-success" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="back-to-cocktails">
    <%= link_to 'Back to Cocktails', cocktails_path, class: "btn btn-primary"  %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload', defer:true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "components/navbar" %>
    <%= yield %>
  <!-- render footer -->
  </body>

</html>